### ISSUE TITLE
Communication through UDP Packet forwarder

### ISSUE THREAD

**Issue by Gillani0** [iegomez/lds#11] opened 2020-04-14 21:24 UTC
Hi,

I tried (and then looked at the code) to send a join request thorough the packet forwarder but it seems like it's only supported with MQTT server. Is there a way (or you thinking of extending it) to send join request and receive it through the packet forwarder. Cheers

Syd

**Comment by scartill** [comment] 2020-04-15 08:23
Hi, indeed the feature is absent, albeit it isn't a complex one. I was thining of extending is anyone needs. Do you have any deadline? I'll try in squeeze in.

P.S. Also, due to lockdown, debugging capabilities are limited, I would propose to use separate branch for a start.

**Comment by Gillani0** [comment] 2020-04-15 08:32
Hi,
Sure a diff branch with the extended capabilities would be great. I don't have any hard deadlines but would be great to have it soonish :) 

For now I'm playing with this (https://github.com/houluy/lora-motes-emulator) for quick tests. However, it doesn't have the detailed features as yours and it contains bugs etc.

**Comment by starsky35** [comment] 2020-04-16 07:13
Hi,
I made some successful tests with my chirpstack server with MQTT. Lds is very helpful tool, thanks for it !
Now, I also wonder how to communicate through UDP, do I need to install extra software like (packet forwarder https://github.com/Lora-net/packet_forwarder) between lds and my chirpstack server or the one in lds is supposed to make the job ?
Please could you also clarify me what is possible to do with the included packet forwarder today ? (I understood from this discussion that device activation feature through UDP is absent)

Thx

**Comment by scartill** [comment] 2020-04-16 07:33
Hi,

No, packet_forwarder is not needed to use UDP, since LDS should simulate it. However data sending procedure is implemented via UDP, while join procedure is WIP.

I'm not quite sure what would be a use case for UDP with chirpstack, the feature was built to be used with servers (like https://github.com/gotthardp/lorawan-server) without distinct "bridge" component.

**Comment by Gillani0** [comment] 2020-04-17 03:48
Hi,

The (Semtech) packet-forwarder is based on the UDP and is commonly used by servers such as ( https://github.com/gotthardp/lorawan-server), Things network (https://github.com/TheThingsNetwork/ttn). Therefore, providing such feature (Joining, sending downlink etc) will generalise your system and can be used with others for testing. 

Syed

**Comment by starsky35** [comment] 2020-04-22 08:45
Hi,

Yep, I confirmed, would be great to have "full features" on packet forwarder.
@scartill in which timeline, do you think we could test it on a separate branch ?

Thanks again.

**Comment by scartill** [comment] 2020-04-23 13:51
@Gillani0 @starsky35 Please check out pull request #17 

For me, this version works in OTAA and ABP modes both with Chirpstack and lorawan-server.

If the version work for you, I will merge it to the `master`.

Thanks!

**Comment by scartill** [comment] 2020-04-28 12:39
Closed by #17

**Closed as completed by scartill** 2020-04-28 12:39 UTC
