### ISSUE TITLE
Windows Platform

### ISSUE THREAD

**Issue by sagar-patel-sls** [iegomez/lds#2] opened 2019-03-26 06:10 UTC
Hii, @iegomez 

i have downloaded release source code but how can i run in windows platform

can you please provide step for open in windows platform

Thanks

**Comment by iegomez** [comment] 2019-03-26 12:48
Hi! I don't use Windows and am not familiar with it, but I believe OpenGL ships with it, so you shouldn't have problems with that. Check [imgui-go](https://github.com/inkyblackness/imgui-go) and the underlying library, [Dear ImGui](https://github.com/ocornut/imgui), for more instructions or issues related to Windows. You should also have gcc (or whatever is used) as the Go library is just a wrapper to a C one and uses cgo.

As for Redis, maybe follow [this](https://redislabs.com/blog/redis-on-windows-10/) or [this](https://redislabs.com/ebook/appendix-a/a-3-installing-on-windows/) and see if it works, or use some ready docker image.

After meeting those requirements, it should just be a matter of building. Be sure to have Go 1.11 or 1.12 installed and Go modules support enabled so that's just a matter of running `make`. I do know that a colleague of mine was able to run it in his Windows machine before I added Redis, so I don't see why you couldn't.

That said, not only don't I use Windows, I don't even have a running installation of it, so I'll probably won't be able to give any Windows specific support. I'll leave this open though in case you face any problems and somebody else is able to help.

**Comment by sagar-patel-sls** [comment] 2019-03-27 04:30
Thanks @iegomez
 can you give me steps of Ubuntu 18.04 system.

**Comment by proffalken** [comment] 2019-03-27 06:36
@sagar-patel-sls the instructions for Ubuntu are the same as for any linux solution:

1) Make sure that Golang and any other dependencies are installed
2) Clone this repository to your Ubuntu Installation
3) Run `make` as documented in the README.md file
4) Run the application

For step 1, you'll need to google that, because it's unique to each distribution as to how you install Golang/OpenGL/etc.

**Comment by iegomez** [comment] 2019-03-27 12:35
@proffalken is right, it'll change among distros and systems. Now, for Ubuntu 18.04 or similar something like this should get your prerequisites ready:
```
sudo apt install build-essential libgl1 libgl1-mesa-dev libgl1-mesa-glx redis-server
```
Then download Go's latest version from https://golang.org/dl/ and follow the instructions.

Finally, clone the repo, cd into it and run `make`. This should install dependencies using Go modules and compile the program into the `gui` executable.

I added this to the readme.

**Comment by sagar-patel-sls** [comment] 2019-03-28 06:42
Hii @iegomez @proffalken 
i follow above step for Ubuntu 18.04 but i still get below screenshot error
![image](https://user-images.githubusercontent.com/43664335/55135805-b3f72f00-5152-11e9-95c8-e7daa77bf7d2.png)
Can you please help me?

Thanks

**Comment by iegomez** [comment] 2019-03-28 12:05
Sorry, I had a bad entry at gitignore so a file wasn't pushed. If you pull from master now it should work.

**Comment by iegomez** [comment] 2019-03-29 14:57
@sagar-patel-sls, dit it work?

**Comment by sagar-patel-sls** [comment] 2019-03-30 04:03
@iegomez  i will try `master` branch

Thank you

**Comment by iegomez** [comment] 2019-04-01 14:30
I also did a new release fixing the issue. I'll wait for your confirmation on this to close it or take any further action.

**Comment by sagar-patel-sls** [comment] 2019-04-02 04:05
@iegomez 
i also try with `master `branch but still i got same error. (OS: Ubuntu 18.04 LTS)

![image](https://user-images.githubusercontent.com/43664335/55375609-6ef44380-552a-11e9-837d-304e13d1c96f.png)

Thank you

**Comment by proffalken** [comment] 2019-04-02 06:49
@sagar-patel-sls You must be missing a library or a step somewhere.

Did you create the `conf.toml` file as specified in the README file?

I can confirm that the current master downloads, compiles, and runs perfectly on my laptop, the only difference is that I'm running Arch Linux instead of Ubuntu (which I wouldn't recommend unless you are *very* familiar with how Linux works!).

Those errors look like strings/variables aren't defined in your configuration file to me...

**Comment by iegomez** [comment] 2019-04-02 12:44
No, those are indeed the functions at `lds/keys.go`, the file that was missing before. So it seems as if the pull from master failed, you are compiling your old version or something is getting cached. I also just downloaded the latest release and compiled it without issues, so I'd recommend that you delete everything concerning the package and download release 0.1.1 or clone the repo again.

**Comment by sagar-patel-sls** [comment] 2019-04-03 05:32
Hii @proffalken @iegomez 

i have tried with `release 0.1.1` also create `conf.toml` file as specified in the README file but i still get error

![image](https://user-images.githubusercontent.com/43664335/55455104-e6e06d80-55ff-11e9-99f3-9b7d893e41e0.png)

Thank you

**Comment by proffalken** [comment] 2019-04-03 06:06
@sagar-patel-sls have you deleted the entire directory, re-cloned the repository and tried again?

(Also, please paste the output of the command here as text rather than screenshots as it is far easier to read.  You can do this by selecting the text in the terminal window, right-clicking, selecting copy, pasting it here and then format it using the `<>` button on the toolbar above)

**Comment by sagar-patel-sls** [comment] 2019-04-03 06:29
@proffalken i have deleted entire directory, re-cloned the `master` repository

please find below output of the command


```
go build -o gui
# github.com/go-gl/glfw/v3.2/glfw
In file included from ../../go/pkg/mod/github.com/go-gl/glfw@v0.0.0-20190217072633-93b30450e032/v3.2/glfw/c_glfw_linbsd.go:24:0:
../../go/pkg/mod/github.com/go-gl/glfw@v0.0.0-20190217072633-93b30450e032/v3.2/glfw/glfw/src/linux_joystick.c: In function ‘_glfwInitJoysticksLinux’:
../../go/pkg/mod/github.com/go-gl/glfw@v0.0.0-20190217072633-93b30450e032/v3.2/glfw/glfw/src/linux_joystick.c:224:42: warning: ‘%s’ directive output may be truncated writing up to 255 bytes into a region of size 9 [-Wformat-truncation=]
             snprintf(path, sizeof(path), "%s/%s", dirname, entry->d_name);
                                          ^~~~~~~
In file included from /usr/include/stdio.h:862:0,
                 from /usr/include/X11/Xcursor/Xcursor.h:26,
                 from ../../go/pkg/mod/github.com/go-gl/glfw@v0.0.0-20190217072633-93b30450e032/v3.2/glfw/glfw/src/x11_platform.h:39,
                 from ../../go/pkg/mod/github.com/go-gl/glfw@v0.0.0-20190217072633-93b30450e032/v3.2/glfw/glfw/src/internal.h:169,
                 from ../../go/pkg/mod/github.com/go-gl/glfw@v0.0.0-20190217072633-93b30450e032/v3.2/glfw/glfw/src/x11_init.c:28,
                 from ../../go/pkg/mod/github.com/go-gl/glfw@v0.0.0-20190217072633-93b30450e032/v3.2/glfw/c_glfw_linbsd.go:19:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:64:10: note: ‘__builtin___snprintf_chk’ output between 12 and 267 bytes into a destination of size 20
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Thank you

**Comment by proffalken** [comment] 2019-04-03 11:35
Thanks.

That seems to be a different error to the one you reported above in regard to the undefined variables?

I suspect that you're missing a dependency somewhere, but I don't know enough about GO to be sure.

**Comment by iegomez** [comment] 2019-04-03 12:22
Actually, those are just warnings related to this issue: https://github.com/go-gl/glfw/issues/213.
Those are pulled in by imgui-go, so I have no control over them, but everything runs fine and they may be ignored for the time being.

**Comment by iegomez** [comment] 2019-04-13 06:58
Hi, @sagar-patel-sls. I've just tested this on a fresh install of Linux Mint and added the missing xorg-dev dependency to the Readme building instructions. That should work for Debian, Ubuntu and mostly any Debian based distro as well, so I'll close this issue for now. Feel free to reopen it if you find any other building issue. Thanks for your report!
And thanks @proffalken for all the help!

Cheers!

**Closed as completed by iegomez** 2019-04-13 06:58 UTC
